const REFERENCES = [
  {
    id: "1",
    type: "interview",
    authorLast: "Fukusawa",
    authorFirst: "Naoto in an interview with Francesca Picchi",
    title: "Super Normal",
    source: "",
    year: "2007",
    publicationPlace: "Baden/Switzerland",
    publisher: "Lars Müller Publishers",
    pageNumber: "106",
    quote: "I believe that in Japan, there is a tendency to take the actual act of using a thing as beauty. This is precisely the beauty of the relationship between objects and people...A form that beautifies behavior and actions, or a form that beautifies the relationship between itself and the things around it, has to be something that does not fix action and environment, but something you might call a generic, overall beauty that grants a degree of freedom."
  },
  {
    id: "2",
    type: "quote",
    authorLast: "Haraway",
    authorFirst: "Donna",
    title: "The Companion Species Manifesto",
    source: "",
    year: "2004",
    publicationPlace: "Chicago",
    publisher: "Prickly Paradigm Press, LLC",
    pageNumber: "6",
    quote: "Many versions of process philosophies help me walk with my dogs in this manifesto. For example, Alfred North Whitehead described 'the concrete' as 'a concrescence of prehensions.' For him, 'the concrete' meant an 'actual occasion.' Reality is an active verb, and the nouns all seem to be gerunds with more appendages than an octopus. Through their reaching into each other, through their 'prehensions' or graspings, beings constitute each other and themselves. Beings do not preexist their relatings. 'Prehensions' have consequences. The world is a knot in motion. Biological and cultural determinism are both instances of misplaced concreteness—i.e., the mistake of, first, taking provisional and local category abstractions like 'nature' and 'culture' for the world and, second, mistaking potent consequences to be preexisting foundations. There are no pre-constituted subjects and objects, and no single sources, unitary actors, or final ends. In Judith Butler's terms, there are only 'contingent foundations;' bodies that matter are the result. A bestiary of agencies, kinds of relatings, and scores of time trup the imaginings of even the most baroque cosmologiests. For me, that is what companion species signifies."
  },
  {
    id: "3",
    type: "quote",
    authorLast: "Franco",
    authorFirst: "'Bifo' Berardi",
    title: "The Uprising: On Poetry and Finance",
    source: "",
    year: "2012",
    publicationPlace: "Los Angeles",
    publisher: "semiotext(e)",
    pageNumber: "43",
    quote: "I am not actually sure what I am talking about when I say the word art. You aren't either—nobody is exactly. Yet it seems that in a recent poll, twenty-four to twenty-five percent of young German people inteviewed by journalists answered the question 'what do you want to be when you're an adult' by stated that they wanted to be artists. What are they picturing? What do they think being an artist means, exactly? Are they thinking about the rich possibilities that the art market offers? Well, maybe, but I don't think so. I think that they are saying that they want to be artists because they feel that being an artist means to escape a future of sadness, to escape a future of precariousness as sadness. They are thinking, well, precariousness and sadness can become something different, something not so sad, not so precarious, if they withdraw their faith, if they withdraw from any expectations a capitalist future can offer. I don't want to expect anything from the future, so I start my future as an artist."
  },
  {
    id: "4",
    type: "quote",
    authorLast: "Franco",
    authorFirst: "'Bifo' Berardi",
    title: "The Uprising: On Poetry and Finance",
    source: "",
    year: "2012",
    publicationPlace: "Los Angeles",
    publisher: "semiotext(e)",
    pageNumber: "140",
    quote: "Poetry is the language of nonexchangeability, the return of infinite hermeneutics, and the return of the sensuous body of language. I'm talking about poetry here as an excess of language, a hidden resource which enables us to shift from one paradigm to another."
  },
  {
    id: "5",
    type: "quote",
    authorLast: "Vilém",
    authorFirst: "Flusser",
    title: "The shape of things: a philosophy of design",
    source: "",
    year: "1999",
    publicationPlace: "London",
    publisher: "Reaktion Books Ltd",
    pageNumber: "26",
    quote: "If 'form' is the opposite of 'matter', then no design exists that could be called 'material': It is always in-forming. And if form is the 'How' of matter, and 'matter' the 'What' of form, then design is one of the methods of giving form to matter and making it appear as it does and not like something else. Design, like all cultural expressions, illustrates that matter does not appear (is not apparent) except in so far as one in-forms it, and that, once in-formed, it starts to appear (become a phenomenon). Thus matter in design, as everwhere in culture, is the way in which forms appear. Nevertheless, to speak of design being between the material and the 'immaterial' is not completey beside the point. There are in fact two different ways of seeing and thinking: the material and the formal. The baroque period was material: The sun is really at the centre, and stoes really fall according to a formula. (It was material and, for precisely that reason, not materialistic.) Our period is more formal: The sun at the centre and the equation of free fall are practical forms. (This is formal, and precisely for that reason not unmaterialistic.) These two ways of seeing and thinking result int wo different ways of designing. The material one results in representations (for example, animal paintings on cave walls). The formal one results in models (for example, designs for irrigation canals on Mesopotamian tablets). The first way of seeing emphasizes the apparent in a form the second way emphasizes the form in the appearance. Thus the history of painting, for example, can be seen as a process in the course of which material seeing (with some set-backs of course) takes on a leading role."
  },
  {
    id: "6",
    type: "quote",
    authorLast: "Maurizio",
    authorFirst: "Lazzarato",
    title: "The Making of the Indebted Man",
    source: "",
    year: "2007",
    publicationPlace: "Los Angeles",
    publisher: "semiotext(e)",
    pageNumber: "46-47",
    quote: "What matters is finance's goal of reducing what will be to what is, that is, reducing the future and its possibilites to current power relations. From this perspective, all financial innovations have but one sole purpose: possessing the future in advance by objectivizing it. This objectivation is of a completely different order from that of labor time; objectivizing time, possessing it in advance, means subordinating all possibility of choice and decision which the future holds to the reproduction of capitalist power relations. In this way, debt appropriates not only the present labor time of wage-earners and of the population in general, it also preempts non-chronological time, each person's future as well as the future of society as a whole. The principal explanation for the strange sensation of living in a society without time, without possibility, without forseeable rupture, is debt."
  },
  {
    id: "7",
    type: "quote",
    authorLast: "Elie",
    authorFirst: "Ayache",
    title: "The Medium of Contingency",
    source: "",
    year: "2015",
    publicationPlace: "Falmouth UK",
    publisher: "Urbanomic Media Ltd",
    pageNumber: "23-24",
    quote: "I'm sure everyone has found that: there is no use really in planning in advance what you are going to write. Even if you do that, chances are that you'll end up writing something different. I think that the true spark of writing comes when you find yourself surprised by what you have written; and I would even claim that there are thoughts that you can only have through the material process of writing."
  },
  {
    id: "8",
    type: "quote",
    authorLast: "Haruki",
    authorFirst: "Murakami",
    title: "Pinball, 1973",
    source: "",
    year: "2015 © 1980 by Haruki Murakami",
    publicationPlace: "New York",
    publisher: "Vintage International",
    pageNumber: "120",
    quote: "We fell silent again. What we shared was no more than a fragment of a time long dead. Yet memories remained, warm memories that remained with me like lights from the past. And I would carry those lights in the brief interval before death grabbed me and tossed me back into the crucible of nothingness."
  },
  {
    id: "9",
    type: "interview",
    authorLast: "McGetrick",
    authorFirst: "Brendan in an interview with Hans Ulrich Obrist",
    title: "Everything You Always Wanted to Know About Curating*",
    source: "",
    year: "2011",
    publicationPlace: "New York",
    publisher: "Sternberg Press",
    pageNumber: "79",
    quote: "However, what is so fascinating about architecture is that architects sometimes succeed in using the book as a medium in their practice, and that's something that Corbusier was the master of. The early books of Christopher Alexander are another example of when books of architecture become something not just about the work, but media through which one can enter the history of ideas."
  },
  {
    id: "10",
    type: "quote",
    authorLast: "Kraus",
    authorFirst: "Chris",
    title: "Where Art Belongs",
    source: "",
    year: "2007",
    publicationPlace: "Los Angeles",
    publisher: "semiotext(e)",
    pageNumber: "48",
    quote: "The job of the poem, it could be said, is to describe the present. And poetry has always been at the dark, secret heart of Bernadette Corporation's work. Pre-Bernadette Corporation, working odd jobs after college, Fletcher and Kelsey rented an office in the then-warehouse district of Chelsea and set themselves up as 'The Agency.' Their principal job was writing (mostly unpublished) collaborative poetry. When the Bernadette Corporation formed several years later, this métier of group work was already familiar. 'Mock incorporation is quick and easy,' they wrote at the time. 'No registration or fees, simply choose a name (i.e., Booty Corporation, Bourgeois Corporation, Buns Corporation) and spend a lot of time together. Ideas will come later.'"
  },
  {
    id: "11",
    type: "quote",
    authorLast: "Kraus",
    authorFirst: "Chris",
    title: "Social Practices",
    source: "",
    year: "2018",
    publicationPlace: "Los Angeles",
    publisher: "semiotext(e)",
    pageNumber: "240",
    quote: "'Art students always ask me what my work is about,' McGinley once remarked. 'I'm always like, 'Fuck, I don't know.' We have adventures; that was always my answer. But at one point I broke it down and realized that it's about contingency.' In Mcginley's world, freed from history, these chance moments are forever foregrounded—as Barthes writes, 'making contingency appear eternal'—and caught between lightness and weight."
  },
  {
    id: "12",
    type: "quote",
    authorLast: "Experimental Jetset",
    authorFirst: "Studio",
    title: "Statement and Counterstatement: Notes on Experimental Jetset",
    source: "",
    year: "2015",
    publicationPlace: "Amsterdam",
    publisher: "Roma Publications",
    pageNumber: "351",
    quote: "A lot of our work is based on this principle: taking a sheet of paper, and folding it in such a way that it suddenly becomes an object. Turning nothing into something. It's all in the folding. Folding is everything. But that's a subject for another lecture. (TLA Lecture, Pratt Instutute, New York, April 8, 2015.)"
  },
  {
    id: "13",
    type: "quote",
    authorLast: "Juhani",
    authorFirst: "Pallasmaa",
    title: "The Eyes of the Skin: Architecture and the Senses",
    source: "",
    year: "2012",
    publicationPlace: "West Sussex UK",
    publisher: "John Wiley & Sons Ltd",
    pageNumber: "13",
    quote: "In creative work, both the artist and crafts(person) are directly engaged with their bodies and their existential experiences rather than focusing on an external and objectified problem. A wise architect works with (their) entire body and sense of self... In creative work, a powerful identification and projection takes place; the entire bodily and mental constitution of the maker becomes the site of the work."
  },
  {
    id: "14",
    type: "quote",
    authorLast: "Dunne, Anthony.",
    authorFirst: "Raby, Fiona",
    title: "Design Noir: The Secret Life of Electronic Objects",
    source: "",
    year: "2001",
    publicationPlace: "London",
    publisher: "Birkhäuser - Publishers for Architecture",
    pageNumber: "6",
    quote: "Future forcasters have a conservative role, predicting patterns of behavior in relation to technological developments. They draw from what we already know about people, and weave new ideas into existing realities. The resulting scenarios extend pre-existant reality into the future and so reinforce the status quo rather than challenging it. Their slick surface distracts us from the dystopian vision of life they wish for. By designing the props for the videos produced to show us what the future could be like, design works to keep official values in place."
  },
]

export default REFERENCES
