import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Taylor Zanke</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>Description</div>
        <div>Latest</div>
      </div>
      <div>
        <div>Contact</div>
        <div>Newsletter</div>
      </div>
      <div>
        <div>Project</div>
        <div>Project</div>
      </div>
    </>
  );
}
